#!/usr/bin/env bash

function do_search() {
	find "${2}" -type f -exec /usr/bin/grep -i -I --with-filename --line-number "${1}" '{}' ';'
}

src_string="${1}"

if [ -z "${src_string}" ]; then
	echo "Usage: $0 [keyword] [[directory]]"
	exit 0
fi

if [ -z "${2}" ]; then
	dir="."
else
	dir="${2}"
fi


do_search "${src_string}" "${dir}" | scb-select
